/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Spring 2016 *
 * Name: Patrick Newhart, Levi Adair, Sam Greenberg, Tom Ficcadenti
 * Date: Apr 20, 2016
 * Time: 2:28:07 AM *
 * Project: csci205FinalProject
 * Package: View
 * File: GameBoardVisual
 * Description:
 *
 * **************************************** */
package View;

import Model.GameManager;
import Model.Tile;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author tjf010
 */
public class GameBoardVisual extends javax.swing.JComponent {
    private GameManager theModel;
//    private Timer timer;
//    private final int DELAY = 25;

    /**
     * Creates new form GameBoardVisualP
     */
    public GameBoardVisual() {
        try {
            initComponents();
            theModel = new GameManager();

        } catch (Exception e) {
            System.out.println("error");
        }
//
//        timer = new Timer();
//        timer.scheduleAtFixedRate(new TimerTask() {
//            @Override
//            public void run() {
//                repaint();
//            }
//        }, 0, DELAY);
    }

    public GameManager getTheModel() {
        return theModel;
    }

    public void setTheModel(GameManager theModel) {
        this.theModel = theModel;
    }

    @Override
    public void paintComponent(Graphics g) {
        System.out.println("painting component");
        g.drawImage(theModel.getBackGround(), 0, 0, this);
        for (Tile[] column : theModel.getTheBoard().board) {
            for (Tile tile : column) {
                Image[] tempImages = tile.getCurrentImages();
                for (int i = 0; i < 4; i++) {
                    g.drawImage(tempImages[i], tile.getPixel()[0],
                                tile.getPixel()[1], this);
                }
            }
        }
        g.drawImage(theModel.getPlayer1().getCurrentImage(),
                    theModel.getPlayer1().getPixel()[0],
                    theModel.getPlayer1().getPixel()[1], this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(672, 864));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                GameBoardVisual gb = new GameBoardVisual();
//                gb.setVisible(true);
//            }
//        });
//    }
}
