/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Spring 2016 *
 * Name: Patrick Newhart, Levi Adair, Sam Greenberg, Tom Ficcadenti
 * Date: May 1, 2016
 * Time: 4:52:44 PM *
 * Project: csci205FinalProject
 * Package: View
 * File: GameOver
 * Description:
 *
 * **************************************** */
package View;

import Model.GameOverManager;
import java.awt.Graphics;

/**
 *
 * @author patricknewhart
 */
public class GameOver extends javax.swing.JPanel {
    private GameOverManager theModel;

    /**
     * Creates new form GameOver
     */
    public GameOver() {
        try {

            initComponents();
            this.theModel = null;

        } catch (Exception e) {
            System.out.println("Error");
        }
    }

    public GameOverManager getTheModel() {
        return theModel;
    }

    public void setTheModel(GameOverManager theModel) {
        this.theModel = theModel;
    }

    @Override
    public void paintComponent(Graphics g) {
        drawMenu(g);

    }

    private void drawMenu(Graphics g) {
        g.drawImage(theModel.getBackGround(), 0, 0, this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
