/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Spring 2016 *
 * Name: Patrick Newhart, Levi Adair, Sam Greenberg, Tom Ficcadenti
 * Date: Apr 20, 2016
 * Time: 2:28:07 AM *
 * Project: csci205FinalProject
 * Package: View
 * File: GameBoardVisual
 * Description:
 *
 * **************************************** */
package View;

import Model.Vector2;
import ModelNew.ModelMain;
import ModelNew.Tile;
import java.awt.Graphics;

/**
 *
 * @author tjf010
 */
public class GameBoardVisual extends javax.swing.JComponent {
    private ModelMain theModel;

    /**
     * Creates new form GameBoardVisualP
     */
    public GameBoardVisual() {
        initComponents();

        this.theModel = new ModelMain();
    }

    @Override
    public void paintComponent(Graphics g) {
        for (Tile[] row : this.theModel.getGameBoard().getBoard()) {
            for (Tile tile : row) {
                int pixelsPerTile = (int) (this.getSize().getHeight() / Vector2.NUM_TILE_VERTICAL);

                int pixelLocX = tile.getBoardX() * pixelsPerTile;
                int pixelLocY = tile.getBoardY() * pixelsPerTile;

                g.drawRect(pixelLocX, pixelLocY,
                           16 * (pixelsPerTile / Vector2.DIVS_PER_TILE),
                           16 * (pixelsPerTile / Vector2.DIVS_PER_TILE));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(
//                    java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                GameBoardVisual gb = new GameBoardVisual();
//                gb.setVisible(true);
//            }
//        });
//    }
}
